name = "web-dao-hang-worker"
main = "_worker.js"
compatibility_date = "2024-01-10"

[vars]
ADMIN_PASSWORD = "admin" # 默认管理密码

[[kv_namespaces]]
binding = "DB"
id = "YOUR_KV_NAMESPACE_ID" # 用户需要替换或通过 wrangler kv:namespace create 创建
